version: '3.9'
services:
  gps_apli:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - gps-net
    depends_on:
      - db

  db:
    container_name: db_gps
    image: postgres:13-bullseye
    restart: unless-stopped
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
    networks:
      - gps-net
networks:
  gps-net: