version: '3.9'

services:

  db:
    container_name: db_gps
    image: postgres:13-bullseye
    restart: unless-stopped
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"